### PR TITLE
Additional global song optimizations

### PR DESCRIPTION
**Pull request by kkevinm**
Further optimized a couple of global songs to save 31 (0x1F) bytes.

### CODE REVIEW

**Comment by KungFuFurby** [comment]
Safe to say you found a use case for the `|` character.

But then there's the Boss Clear song... why was it revised from `q6b` to `q69`? This kind of modification is causing me to think about my ASM method of generating this kind of stuff musically speaking, because at least in theory, I can instead generate the duration and the quantization bytes *outside* of the loop.

Or alternatively, only have the first note generate itself, then have everything else be inside a label, so that the quantization is set correctly, but it still saves some memory overall.

**Comment by kkevinm** [comment]
> Safe to say you found a use case for the `|` character.

lol, yeah. I think the same trick would also work with `h0` or redefining the octave, if you think using `|` can potentially be unsafe.

> But then there's the Boss Clear song... why was it revised from `q69` to `q6b`? This kind of modification is causing me to think about my ASM method of generating this kind of stuff musically speaking, because at least in theory, I can instead generate the duration and the quantization bytes _outside_ of the loop.

It's still `q6b` in #6, for #7 I changed `q69` to the equivalent `v214` (0x5A/0x6B * v255) outside of the loop. Reason is normally the quantization is redefined at the start of loops so you can't do something like `qXY * qZW *` with different quantizations. If you changed that then yeah I guess you can use `q69` instead of `v214` there.


On an unrelated note, could also the `y10`s at the start of channels be dropped? If global songs work the same as locals, then panning would be reset, so a few bytes can be saved by removing those as well (and I think you fixed potential issues with not having a panning command like surround not get reset at the start of the song).

**Comment by KungFuFurby** [comment]
Oh. So you're substituting note velocity for something else. Well played.

And yes, if you want to go further on your optimizations, `y10` is safe to remove because of the resolution of #322 and #353.

**Comment by kkevinm** [comment]
> And yes, if you want to go further on your optimizations, `y10` is safe to remove because of the resolution of #322 and #353.

Alright, I'll add that as well tomorrow then!

**Comment by kkevinm** [comment]
Alright, I made the additional optimizations saving other 64 bytes (so 95 in total).
Besides removing the `y10` at the beginning of the channels, I manually optimized long notes (using the `|` trick once again) since AMK defaults to using 96 ticks for splitting them, but in some cases it's better to use different lengths (you can see for example `4.|^4.` instead of `2^4` or `=92|^=92|^=92` instead of `=84^2^2`).
Additionally, I noticed the Boss Clear music had a slight inaccuracy due to using `^8` in channels `#1` and `#2` after calling the new instrument when the intro whistle ends: this caused the AMK version to have a slightly audible `@4` playing for an eigth note in those two channels after the intro, while in the originals the channels just key off. I replaced the ties with rests to fix that.

**Comment by KungFuFurby** [comment]
You're right on the Boss Clear song. The original conversion failed to account for the phrase end marker causing a key off.

I briefly hesitated because of the original notes in the .txt files still referring to phrase boundaries, but I ultimately decided to relent. So away we go.

**Pull request merged**
